name: Security Audit

on:
  push:
    branches:
      - master
    paths:
      - '**/Cargo.toml'
  schedule:
    - cron: '0 7 * * 1' # run at 7 AM UTC on Monday

jobs:
  security-audit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2

      - name: Audit Check
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
